### ISSUE TITLE
resize error

### ISSUE THREAD

**Issue by linuxwit** [yanhaijing/zepto.fullpage#1]
在手机浏览器中，由于手机浏览器会自动隐藏地址栏会出现不充满全屏的情况

**Comment by yanhaijing** [comment]
hi 可以提供下你的手机型号
现在没有做resize和旋转的处理
这个后序会加上

**Comment by yanhaijing** [comment]
hi maste分支最新代码已经修复了这个问题，在屏幕旋转和尺寸改变时会重新渲染
同时还带了很多新特性包括但不限于增强的事件，暴漏的方法，及丰富的demo

**Comment by linuxwit** [comment]
谢谢
