### ISSUE TITLE
Android 移动端 Chrome V61 下无法整屏垂直滚动

### ISSUE THREAD

**Issue by g8up** [yanhaijing/zepto.fullpage#100]
滚动时不能整屏翻滚。
通过远程调试看到 console 出现 warning：

>[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

**Comment by yanhaijing** [comment]
试了一下 安卓 7.1.1 chrome 61.0.3163.98 是可以的，能够提供下demo

**Comment by g8up** [comment]
我怀疑是因为滑动时 chrome 的地址栏部分会挤压屏幕高度，导致插件计算错误。请求大大协助~

DOM 结构如此：
![chrome_2017-10-11_23-57-30](https://user-images.githubusercontent.com/8005686/31452174-bf0b5396-aee0-11e7-9b2e-b1556b4336d1.png)

是 fis3 + vue 的项目，绑定 fullpage 通过这个语句：
```
$('#fullpage').fullpage({
  der: 0.1,
});
```

**Comment by yanhaijing** [comment]
<img width="684" alt="wx20171012-124800 2x" src="https://user-images.githubusercontent.com/3192087/31479722-b0f47b36-aede-11e7-8304-7924b894203b.png">
使用方法不对，wp是必不可少的，注意wp的overflow，并且不能给wp和wp-inner设置高度

**Comment by g8up** [comment]
经过您的提醒，我给`.middle`添加 `overflow: hidden` 后，解决问题， not a bug。
Thx！
