### ISSUE TITLE
IOS10下的Webview中 双击整体webview内容上移

### ISSUE THREAD

**Issue by zuochenxue** [yanhaijing/zepto.fullpage#102]
### 问题是什么
IOS10下的Webview中 双击整体webview内容上移 不用插件无此问题

### 环境
- 手机: iphone 6s
- 系统：IOS10
- 浏览器：webview
- zepto版本：最新demo均有问题
- zepto.fullpage版本：最新demo均有问题

### 在线例子
如果有请提供在线例子

### 其他
其他信息
出问题的截图： http://47.88.155.63/testLib/webview.jpg

**Comment by yanhaijing** [comment]
解决了吗？
