### ISSUE TITLE
zepto.fullpage.js怎么取消触屏滑动事件，只保留点击滑动事件？

### ISSUE THREAD

**Issue by yanhaijing** [yanhaijing/zepto.fullpage#12]
http://segmentfault.com/q/1010000002716472?_ea=188272

**Comment by yanhaijing** [comment]
请问你想实现的是取消向上，而点击切换吗？
可以用如下的方式：

```
$.fn.fullpage.stop();//阻止事件
//自定义事件，并手动切换
$().on('tap', function (e) {
    $.fn.fullpage.moveNext();
});
```

为了阻止过快切换，可以设置duration 属性

**Comment by ibcLee** [comment]
Get！

**Comment by web-oop** [comment]
我也遇到了 这个问题，很奇怪的是，还没有调用fullpage()的时候，页面就不能滚动了。是加载了zepto.fullpage.js就不能滚动。有点尴尬。

**Comment by web-oop** [comment]
并且$.fn.fullpage.stop(); 这个页面某个容器overflow:scroll仍然没有作用。

**Comment by yanhaijing** [comment]
@web-oop 加载就不能滚动这不可能，执行的时候才会阻止默认的事件，zepto.fullpage在document上绑定了touchmove事件，并且阻止了默认事件preventDefault

```js
$(document).on('touchmove', touchmove);
```

可以通过下面的api来开启阻止和关闭阻止
```jsx
$.fn.fullpage.holdTouch() // 阻止，默认阻止
$.fn.fullpage.unHoldTouch() // 关闭阻止
```
`$.fn.fullpage.stop()`中已经调用了`$.fn.fullpage.unHoldTouch()`，所以应该没有问题，你用的哪个版本？是最新的吗？

**Comment by web-oop** [comment]
不好意思 ，我拿的是以前用过的版本，旧版会这样 新版没试过。谢谢了。

**Comment by yanhaijing** [comment]
@web-oop 新版应该修复了这个问题

**Comment by DereKEasH** [comment]
@yanhaijing  如何禁止手动滑动这个功能？ 我想要实现点击跳转？ 有API吗？ 禁止手动滑动的api

**Comment by yanhaijing** [comment]
@DereKEasH 这个issue给的代码就可以
