### ISSUE TITLE
第71行建议修改下

### ISSUE THREAD

**Issue by huqiliang** [yanhaijing/zepto.fullpage#14]
第71行建议修改下 this.height = $(window).height();

**Comment by yanhaijing** [comment]
hi，首先感谢你提出宝贵的建议，但这个我不能接受，原因如下：
zepto.fullpage 可以在页面区域内使用，而不是整个屏幕，而且，下一个版本，计划一个页面内可以存在多个实例

**Comment by huqiliang** [comment]
哦 这样子的 我是发现页面背景显示到下面去了 感谢你的插件 目前使用还不错

**Comment by yanhaijing** [comment]
# 

哦 这样子的 我是发现页面背景显示到下面去了 感谢你的插件 目前使用还不错

@huqiliang 这个是什么意思，我不太明白
注：如果有线上的项目在使用的话，可以把地址发我，我在收集使用的项目

**Comment by huqiliang** [comment]
没有上线 可能跟我的使用环境有关系

**Comment by huqiliang** [comment]
没有上线 可能跟我的使用环境有关系

**Comment by yanhaijing** [comment]
好的有什么问题可以写出来，一起探讨，真个代码都经过生产环境的考研，兼容列表里面写的环境都经过严格测试，不应该会有兼容性的问题。
