### ISSUE TITLE
现在的zepto.fullpage不支持超出内容出滚动条啊，这个可以加进去吗，期待您的回复

### ISSUE THREAD

**Issue by yanhaijing** [yanhaijing/zepto.fullpage#16]
现在的zepto.fullpage不支持超出内容出滚动条啊，这个可以加进去吗，期待您的回复

我叫小马

**Comment by yanhaijing** [comment]
hi你好，
这个要实现的是单页滚动效果，超出内容除滚动条这个逻辑很奇怪，不知道你想在什么场景下应用呢，这个想不出加的理由

**Comment by jiadaoyun** [comment]
有些页面内容过多，比如文字图片什么的。
我知道目前实现的是单页全屏切换效果，JQ-fullpage是有这个功能了，现在不是觉得您的东西好，想学习一下

**Comment by yanhaijing** [comment]
hi 你好，提供以下jqfullpage 超出滚动的demo最好不过了

**Comment by jiadaoyun** [comment]
大牛好，他的文件比较容易找到，具体配置如下：

$(function(){
    $('#jinxin').fullpage({
        scrollOverflow:true,
    });
});

文件地址：
https://github.com/alvarotrigo/fullPage.js

**Comment by yanhaijing** [comment]
好的感谢反馈 我研究一下，有什么问题就提出来

**Comment by yanhaijing** [comment]
@jiadaoyun 看了一下demo，这个和普通的页面没区别啊，这个属性有些鸡肋

**Comment by jiadaoyun** [comment]
目的就是为了解决页面过多，而超出一屏后的处理方法啊，我现在真的需要。

**Comment by yanhaijing** [comment]
@jiadaoyun zepto.fullpage 主张简单，尽量把事情都交给用户去做，只做核心功能，而且是专注于移动端，对于移动端的小屏，建议用媒体查询，做一下响应式，或隐藏掉无关元素
如果你特别需要这个功能，可以尝试修改下，并发个pr thx

**Comment by logoove** [comment]
我也遇到这个问题 没找到解决办法

**Comment by yanhaijing** [comment]
@logoove 目前没有计划，你可以自己实现
