### ISSUE TITLE
引导页转到正常页

### ISSUE THREAD

**Issue by lizheming** [yanhaijing/zepto.fullpage#18]
http://weibo.com/1649383554/Cgqjm0WmI
请问 fullPage 做的引导页然后再转入正常的 responsive 网站页面这种需求（就和平常开 App 有个介绍页一样）应该怎么做？

**Comment by yanhaijing** [comment]
fullpage可以内嵌到父元素，其定位什么的都依赖父元素，可以将父元素隐藏掉就可以了，然后将正常网页显示，也可以跳转到其他页面哈，感觉就是一个隐藏 显示的过程

**Comment by lizheming** [comment]
如何做到滑动到最后一下的时候显示父元素呢？

**Comment by yanhaijing** [comment]
https://github.com/yanhaijing/zepto.fullpage/blob/master/doc/api.md 的 change属性可以做到，可以看一下文档
