### ISSUE TITLE
最后一页向倒数第二页滑动的时候会有闪屏。

### ISSUE THREAD

**Issue by rrkelee** [yanhaijing/zepto.fullpage#19]
![](http://ww3.sinaimg.cn/large/acf60cddgw1es44pnfb1dj20u01hc42t.jpg)

**Comment by yanhaijing** [comment]
如果能提供你程序的线上访问地址就更好了，方便我排查问题，或者你用demo里的例子试一下有没有这个问题，确定下是否是zepto.fullpage的问题

**Comment by rrkelee** [comment]
是我自己的问题。。。sorry。。。

![](http://ww3.sinaimg.cn/large/acf60cddgw1es4rmpg0lej204a04gaa1.jpg)

**Comment by yanhaijing** [comment]
没关系，感谢积极反馈问题。
注：如果有线上链接，欢迎发到 #9
