### ISSUE TITLE
在mac下demo文件夹里的demo页面都运行不起来？

### ISSUE THREAD

**Issue by mcattx** [yanhaijing/zepto.fullpage#24]
我 `git clone`项目到本地后，直接在`chrome`浏览器打开`basic.html`，发现在`chrome`的手机模拟器里模拟向上滑动没效果，但是`console`控制台也没有报错，我设置了断点发现`js`也有执行。

运行环境：
OSX: 10.9.5
Chrome: 42.0.2311.152（64-bit）
项目版本: zepto.fullpage.js v0.3.1

另外，我在windows下`git clone`项目直接打开`basic.html`，发现在`chrome`的手机模拟器里模拟向上滑动正常。

**Comment by yanhaijing** [comment]
hi 你好，可否看一下父元素的样式，是否失效了？我这没有mac (┬＿┬)

**Comment by mcattx** [comment]
@yanhaijing  父样式没问题。

```
.wp {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  overflow: hidden;
}
```

**Comment by yanhaijing** [comment]
hi 你好，我是说看下控制台中，wp-inner的transform 属性是否挂了，这个是用js计算的，可能有兼容性问题，麻烦帮忙看下，我这边没有环境

**Comment by hacke2** [comment]
哈哈，@yanhaijing 该整个mac了， 我这边没问题

运行环境：
OSX: 10.10.3
Chrome: 43.0.2357.81 (64-bit)
项目版本: zepto.fullpage.js v0.3.1

**Comment by yanhaijing** [comment]
@hacke2 感谢反馈，坐等公司给发mac了 :-)

**Comment by mcattx** [comment]
@yanhaijing 今天再试了一下发现可以了。@-@
可以把这个 issue 关掉了。

**Comment by yanhaijing** [comment]
@titancat 感谢反馈，是不是你把chrome升级了 :-)
