### ISSUE TITLE
百度知道App5.0中的动画是如何实现的？

### ISSUE THREAD

**Issue by techbirds** [yanhaijing/zepto.fullpage#25]
求指点。

**Comment by yanhaijing** [comment]
zepto。fullpage的原理就是给当前页，添加一个cur class，你可以在这个cur class下做做动画

```
.page1 .div1 {1}
.page1.cur .div1 {2}
//1 处是原始css
//2出填 动画 可以是transition 或 animation
```

**Comment by techbirds** [comment]
恩，非常感谢，还有就是关于其元素的动画例如淡入淡出，动画移动等等效果是如何实现的？

**Comment by yanhaijing** [comment]
@techbirds 这些都是css3的transition 或 animation

**Comment by techbirds** [comment]
恩，那我学习下。thx。

**Comment by techbirds** [comment]
麻烦多问一句,百度知道APP5.0中的下载连接如何自动跳转至AppStore的？链接是应用宝微信的移动推广连接，我的应用貌似只支持Android系统的跳转下载。IOS点击则提示「抱歉，当前不支持IOS版的下载」。但是我IOS也提交了对应的AP，难道应用宝需要与Appstore绑定什么吗？

**Comment by yanhaijing** [comment]
我这边就是百度知道在appstore的链接，就可以了

**Comment by techbirds** [comment]
不是把，这是百度知道的下载连接：http://a.app.qq.com/o/simple.jsp?pkgname=com.baidu.iknow

**Comment by yanhaijing** [comment]
哦 对了 微信里是要放应用宝的链接才可以，要放app在应用宝的链接，不然会被拦截

**Comment by techbirds** [comment]
恩是的，那么问题就是应用宝貌似只对android分发的吧。该连接如何做到区分ios/android OS的并能自动跳转至相应的市场？

**Comment by yanhaijing** [comment]
应用宝自己会做跳转的，ios就会自动跳到appstore

**Comment by techbirds** [comment]
anyway thx.
