### ISSUE TITLE
单页高度手动设置成100vh后 自动计算后的高度比设备高度 要高出很多

### ISSUE THREAD

**Issue by Kaijun** [yanhaijing/zepto.fullpage#27]
例如我有3个pages, 每页都设置成height: 100vh. 通过pullpage之后, 实际高度 大概是2倍的100vh, 不知道能否解决?

**Comment by Kaijun** [comment]
同时我也在想 为何设计上不直接用vh作为高度计量标准, 这样子会有什么不妥的地方吗?

**Comment by yanhaijing** [comment]
hi你好，首先感谢你使用fullpage
由于我对vh不是很了解，你可否给我发一个有问题的demo，研究一下，现在的高度是通过js计算的，获取的是父元素的高度

**Comment by Kaijun** [comment]
@yanhaijing 
感谢你的解答, 看了下源码 原来获取的是最外层wp的高度, 因为我之前没有手动设置过wp的样式, 所以导致wp被自动填充成所有页面高度. 

至于我说的100vh 我的意思是 Fullpage实例的this.height 可以不取父元素的高度 直接 等于100vh(就是设备的高度)

**Comment by yanhaijing** [comment]
hi这个其实还是和我开始想着不实现单例的形式有关系（#30 有提到），比如想着屏幕内的一小块区域可以自己滚动，所以才获取的是父元素的高度，这个其实在readme中有重点强调 wp要固定高度
