### ISSUE TITLE
js追加，插件失效？？？？？？？

### ISSUE THREAD

**Issue by shenyulin** [yanhaijing/zepto.fullpage#29]
执行以下操作后插件失效？？？？？？？？？？？？？
1、隐藏wrap；
2、JS往wp-inner容器中追加内容，如下：
  <div class="page">
          <img src="../../Content/images/order3.jpg" alt="" />
   </div>

3、显示wrap，并执行

**Comment by yanhaijing** [comment]
hi图片挂了，咋回事

插件需要获取wrap的高度，来确定每个的高度，隐藏了就不获取高度了，所以不能隐藏
