### ISSUE TITLE
Why don't you use 'translateY'.

### ISSUE THREAD

**Issue by luciy** [yanhaijing/zepto.fullpage#3]
Why don't you use 'translateY'.

**Comment by yanhaijing** [comment]
hi 你好，首先欢迎反馈
这是因为安卓2.3不支持translate
后序准备做个兼容处理，支持translate的优先用translate

**Comment by yanhaijing** [comment]
http://caniuse.com/#search=transform

**Comment by luciy** [comment]
如果需要兼容安卓2.3得话确实需要做一个兼容处理，因为利用top并没有translateY性能好，至少在兼容的手机上是这样。
还有就是动画利用transition，而moveTo函数中确定动画结束是利用setTimeout，是否考虑利用webkitTransitionEnd来解决动画结束后回调哦。

**Comment by yanhaijing** [comment]
第一个问题是要解决的，后序会做一个兼容处理，感谢反馈
第二个问题 我还没想好，timeout的好处是可以自定义这个时间，因为可能作者希望本屏动画全部播放完才能切换，而不是切换的动画完成，这个还要在考虑下，感谢反馈

**Comment by mask2012** [comment]
没什么，就是来赞一下

**Comment by yanhaijing** [comment]
感谢支持

**Comment by jerrylau91** [comment]
关注一下！

**Comment by yanhaijing** [comment]
感谢大家的支持

**Comment by dolymood** [comment]
其实不是android2.3不支持transform，是不支持3d transform，还有bug，其实从2.1就开始支持了
，但需要前缀。在fullpage的场景里，使用起来问题不大。参见 https://developer.mozilla.org/en-US/docs/Web/CSS/transform

**Comment by yanhaijing** [comment]
嗯 好的多谢反馈 原来我使用caniuse的方法有误，导致以为从4.0才开始兼容，这个问题过一段时间修好，会在0.2.0版本中带来
