### ISSUE TITLE
建议把箭头合到插件里

### ISSUE THREAD

**Issue by diamont1001** [yanhaijing/zepto.fullpage#31]
建议把Demo里的Arrow合到插件里，默认箭头。
有修改箭头样式需求话，大家可以自己在custom.css里自己修改

**Comment by yanhaijing** [comment]
首先感谢您提出宝贵意见，但是，sorry这个实现非常简单，而且也不是核心功能，zepto.fullpage的核心思想是只做该做的事，并把该做的事做到最好，所以这个请求不能接受
