### ISSUE TITLE
效果

### ISSUE THREAD

**Issue by maicss** [yanhaijing/zepto.fullpage#32]
百度知道不能滚动；百度经验的文字图片拉伸的简直不能看；还有这个和www.dowebok.com/77.html这个有关系吗

**Comment by maicss** [comment]
百度知道不能滚动；百度经验的文字图片拉伸的简直不能看；还有这个和www.dowebok.com/77.html这个有关系吗

**Comment by yanhaijing** [comment]
@maicss 
1. 我看到百度知道是能滚动的，经验的拉伸是自己搞的，和zepto.fullpage 无关哈
2. 当然有关系，都是为了实现同一个效果，只是平台不一样
