### ISSUE TITLE
大侠好！

### ISSUE THREAD

**Issue by jiadaoyun** [yanhaijing/zepto.fullpage#33]
我想问下怎么获取当前页面啊，就是在当前屏的时候，我想做一些其他的操作，比如把最下面的引导箭头给隐藏掉。
我是纯小白见谅。。

**Comment by yanhaijing** [comment]
使用change事件，change事件中会传入当前屏
doc https://github.com/yanhaijing/zepto.fullpage/blob/master/doc/api.md
demo https://github.com/yanhaijing/zepto.fullpage/blob/master/demo/event.html
