### ISSUE TITLE
用了这个框架之后，页面上一些要滚动的元素就滚动不了了。

### ISSUE THREAD

**Issue by oadaM92** [yanhaijing/zepto.fullpage#39]
例如我有一个弹出框，弹出框里面有很长的内容，我设置了max-height，并且overflow:scroll，但是滚动不了。同样的代码，不用这个框架就可以滚动了。是这个框架监听了相关事件的原因吗？有什么解决方法吗？

**Comment by oadaM92** [comment]
$(document).on('touchmove', function(e) {
        e.preventDefault();
    });
我把上面的e.preventDefault();注释掉就可以了。 e.preventDefault();这段代码有必要吗？

**Comment by oadaM92** [comment]
原来删除了之后在微信上用就有问题了。。。

**Comment by yanhaijing** [comment]
这个是这样的，在有些浏览器里，上下左右滑动是有语义的，比如前进后退等，如果不禁止掉这个，特别影像体验，所以不能去掉

关于元素内部的滚动问题，我也只没找到好的解决办法，那个iscroll 可以解决不，其实原理就是在元素上绑定touchmove事件，自定义滚动的动作，我暂时没啥解决办法

**Comment by oadaM92** [comment]
嗯，谢谢解答。我现在的解决方法就是需要内部滚动的时候取消监听这个事件：$(document).off('touchmove');
不需要滚动的时候再绑定这个事件。

**Comment by yanhaijing** [comment]
可以这样hack一下，但是需要写好注释
