### ISSUE TITLE
能否做一个demo，滑动时，每一屏都有CSS3动画的那种，我是新手，不知道js怎么实现~~

### ISSUE THREAD

**Issue by bokebi** [yanhaijing/zepto.fullpage#45]
主要是滑动一屏时，JS是怎么添加动画，做个这种demo，让我们这些新手学习一下吧，百度的那些demo效果很不错，可惜js看不懂~~~~~

**Comment by yanhaijing** [comment]
@bokebi 首先感谢使用，这个我后续加上，zepto.fullpage主张动画都通过css自己来写，会在每一屏当前屏上添加.cur class的，也暴露了当前是第几屏的js接口，也可使用js实现

**Comment by yanhaijing** [comment]
#25 这里有一个css动画的简单的原理解释
