### ISSUE TITLE
页面切换底部闪屏问题

### ISSUE THREAD

**Issue by Leeiio** [yanhaijing/zepto.fullpage#46]
把示例中的page样式都改成黑色背景，可以更直观地看到闪屏

```
.page1{
    background: black;
}
.page2{
    background: black;
}
.page3{
    background: black;
}
.page4{
    background: black;
}
```

上划切换页面，会发现底部有白色闪烁，求解

**Comment by yanhaijing** [comment]
求 系统版本 浏览器版本 哈

**Comment by Leeiio** [comment]
iOS 9.2，iPhone  5s，微信内置浏览器

**Comment by yanhaijing** [comment]
@Leeiio 其他平台有试吗？也有同样的问题？

**Comment by taomas** [comment]
我用微信和QQ访问也是的，但是用QQ浏览器不会出现白色闪烁，用UC浏览器个别页面没动画，直接闪一下就过了。

**Comment by Leeiio** [comment]
@wendaosanshou 你可以试试微信后台退出，然后重新打开看看是不是还这样，我之前的问题是因为微信自己的内存泄露，已经向微信团队求证过

**Comment by wendaosanshou** [comment]
@Leeiio 应该不是微信的内存泄露，我有两个类似的页面，其中一个从第三个页面开始会出现闪白，另外一个没出现过这种情况。两个在QQ浏览器中使用都不会出现闪白问题。

**Comment by taomas** [comment]
现在好了，是因为底部用了一个绝对定位的div导致出现了闪白现象。现在用fixed放在最外层就没有出现了。
