### ISSUE TITLE
为何height会是3150px？在mobile上

### ISSUE THREAD

**Issue by claire1028** [yanhaijing/zepto.fullpage#54]
$('.wp-inner').fullpage();报错说fullpage 为undefined? 我用Zepto('.wp-inner').fullpage()这样就可行，但是渲染出来的height却是3150px，测试环境是iphone6。

**Comment by yanhaijing** [comment]
第一个问题：你的$ 可能不是zepto
第二个问题：你说的高度是谁的高度？那个高度会是包含全部子元素的高度，然后需要给父元素的overflow设置为hidden，实现滚动
