### ISSUE TITLE
 e.preventDefault();

### ISSUE THREAD

**Issue by polly343900** [yanhaijing/zepto.fullpage#6]
是为了阻止冒泡么？这样导致页面里的锚点标签无法跳转了。。:)

**Comment by yanhaijing** [comment]
hi 你好preventDefault实在父元素上，不会阻止页面内部的a标签的

**Comment by yanhaijing** [comment]
这个问题参看 #8 的解决方法

**Comment by yanhaijing** [comment]
这个问题现在以修复，[v0.3.1](https://github.com/yanhaijing/zepto.fullpage/releases/tag/v0.3.1) 后不再阻止
