### ISSUE TITLE
提一个关于在pc端展示的疑惑

### ISSUE THREAD

**Issue by ouzhou** [yanhaijing/zepto.fullpage#78]
我看到很多网站都先是在pc端有一个展示，然后有一个二维码，可以在移动端扫描，我就想问问，有没有什么办法用这个插件，在pc端有个可以**模拟手机屏幕**，并且鼠标拖动多少那个小手机内部就移动多少

**Comment by ouzhou** [comment]
![image](https://cloud.githubusercontent.com/assets/7693866/17454932/9d958da8-5bda-11e6-9b13-e0feceace2d7.png)

链接 http://h5.baidu.com/

**Comment by yanhaijing** [comment]
hi 你好，我想到的思路是，做一个展示页，用iframe连接到活动页面，但需要自己实现在pc端的交互

**Comment by ouzhou** [comment]
我看到他的代码是用的iframe  。 然后我想知道他是怎么做到pc访问是一个展示页面，移动端访问同一个地址变成了移动端的页面，我想的是判断设备然后针对pc还是移动端 隐藏或者展现一部分元素，请问我的这个思路对吗？

**Comment by yanhaijing** [comment]
可以在ngix层进行重写吧！

**Comment by ouzhou** [comment]
感觉重写成本高了 还不如去掉多余的节点
