### ISSUE TITLE
有些问题反馈，希望项目越来越好

### ISSUE THREAD

**Issue by vvkee** [yanhaijing/zepto.fullpage#8]
1、是否不支持左右滑动，在move事件中只有Y轴的计算
2、回调函数，befor与after的索引问题
3、不支持循环滚动

最后，感谢您的分享！谢谢

**Comment by yanhaijing** [comment]
感谢您的反馈
1. 这个已经在议程之中
2. 这个问题可否说的详细些，没明白
3. 这个也在议程中

最近忙于其他项目，过段时间会开发这些功能

**Comment by yanhaijing** [comment]
3、 见https://github.com/yanhaijing/zepto.fullpage/issues/3

**Comment by zdpdsy** [comment]
1.滑动的页面中放个a标签，点击无反应

**Comment by yanhaijing** [comment]
@zdpdsy 你好 有这个问题吗？没有吧？见 #6

**Comment by zdpdsy** [comment]
确实没反应 
加了个a标签 代码如下
![qq 20150416200405](https://cloud.githubusercontent.com/assets/7123339/7180463/a27700e2-e474-11e4-9bd9-b4fc1406d2f9.png)

在谷歌下模拟iphone5运行环境，点击这个a标签无效

**Comment by yanhaijing** [comment]
嗯 试了一下确实是这样的，可以添加如下代码加以解决：

```
$(document).on('tap', 'a', function (e) {
    location.href = this.href;
});
```

**Comment by yanhaijing** [comment]
@zdpdsy 1.滑动的页面中放个a标签，点击无反应
这个问题现在以修复，[v0.3.1](https://github.com/yanhaijing/zepto.fullpage/releases/tag/v0.3.1) 后不再阻止
参考 #6
