### ISSUE TITLE
input框和按钮不能选中、点击。

### ISSUE THREAD

**Issue by nikolausliu** [yanhaijing/zepto.fullpage#98]
是不是源码中禁用了点击事件。因为我在页面中注册的所有点击事件都没用。

**Comment by yanhaijing** [comment]
在document上禁止了 touch事件，可以使用$.fn.fullpage.unholdTouch 解除这个禁止，禁止这个是为了屏蔽掉Safari里面默认的下拉动画

**Comment by yanhaijing** [comment]
还可以在你input的父元素绑定一个 touchmove事件，然后阻止冒泡，应该也可以

**Comment by yanhaijing** [comment]
相关参考 #74 #11

**Comment by nikolausliu** [comment]
好的，谢谢
